### ISSUE TITLE
Falla compilación en strider

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/conectar-educativo#19]
Al querer compilar el paquete en strider aparece un error de npm:

http://ci.huayragnulinux.com.ar/huayralinux/conectar-educativo/

Estimamos que es muy similar al issue de compartirweb https://github.com/HuayraLinux/huayra-compartirweb/issues/4

**Comment by iglosiggio** [comment]
Lo cierro porque ya está andando (http://ci.huayragnulinux.com.ar/huayralinux/conectar-educativo/job/57d83adbfb05c84525c3bb54)
